POST http://localhost:8010/users HTTP/1.1
content-type: application/json

{
    "Id": "1234",
    "name": "shay"
}

### 

GET http://localhost:8010/users HTTP/1.1



### 

GET http://localhost:8010/users/1 HTTP/1.1